"""initial_schema

Revision ID: e92c73f66541
Revises: 
Create Date: 2026-03-31 03:02:11.317123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e92c73f66541'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandatory_maintenance_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_code', sa.String(length=50), nullable=True, comment="A qué modelo aplica. NULL o 'ALL' para aplicar a todos"),
    sa.Column('maintenance_number', sa.Integer(), nullable=False, comment='El índice cronológico. 1, 2, 3...'),
    sa.Column('km_target', sa.Integer(), nullable=False, comment='Kilometraje esperado para el mantenimiento, Ej: 500'),
    sa.Column('tolerance_pre_km', sa.Integer(), nullable=True, comment='Cuántos KM ANTES puede presentarse (Ej 400)'),
    sa.Column('tolerance_post_km', sa.Integer(), nullable=True, comment='Cuántos KM DESPUÉS puede presentarse (Ej 700)'),
    sa.Column('is_free_labor', sa.Boolean(), nullable=True, comment='True para la revisión de los 500, etc.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_catalog',
    sa.Column('part_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('public_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_wear_part', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('part_code')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent_to_supplier', 'in_production', 'ready_factory', 'at_port', 'in_transit', 'at_customs', 'received', 'partial_received', name='purchaseorderstatus'), nullable=False),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('container_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tenant_type', sa.Enum('service_center', 'parts_dealer', name='tenanttype'), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('capacidad_bahias', sa.Integer(), nullable=True),
    sa.Column('numero_tecnicos', sa.Integer(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('vehicle_limited_warranties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_code', sa.String(length=50), nullable=True, comment="A qué modelo aplica. NULL o 'ALL' para referirse a la política universal."),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('covered_km', sa.Integer(), nullable=False, comment='Ej: 1000'),
    sa.Column('covered_days', sa.Integer(), nullable=False, comment='Ej: 30'),
    sa.Column('exclusion_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vin_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('engine_number', sa.String(length=50), nullable=True),
    sa.Column('model_code', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('assembly_date', sa.Date(), nullable=True),
    sa.Column('garantia_motor_km', sa.Integer(), nullable=True, comment='Kilómetros de cobertura para el motor'),
    sa.Column('garantia_motor_meses', sa.Integer(), nullable=True, comment='Meses de cobertura para el motor'),
    sa.Column('garantia_general_km', sa.Integer(), nullable=True, comment='Kilómetros de cobertura general'),
    sa.Column('garantia_general_meses', sa.Integer(), nullable=True, comment='Meses de cobertura general'),
    sa.Column('warranty_months', sa.Integer(), nullable=True),
    sa.Column('warranty_km', sa.Integer(), nullable=True),
    sa.Column('km_reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('km_reviews_free', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdi_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('review_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warranty_hour_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('part_code', sa.String(length=100), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'received', 'backorder', name='purchaseorderitemstatus'), nullable=True),
    sa.ForeignKeyConstraint(['part_code'], ['part_catalog.part_code'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'technician', 'client', 'parts_dealer', name='role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'rejected', name='userstatus'), nullable=False),
    sa.Column('service_center_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('parts_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'sent_to_softway', name='partsorderstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('softway_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('received', 'scheduled', 'in_progress', 'on_hold_parts', 'rescheduled', 'on_hold_client', 'external_work', 'completed', 'delivered', 'cancelled', name='servicestatus'), nullable=False),
    sa.Column('service_type', sa.Enum('regular', 'warranty', 'km_review', 'pdi', name='servicetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('received', 'scheduled', 'in_progress', 'on_hold_parts', 'rescheduled', 'on_hold_client', 'external_work', 'completed', 'delivered', 'cancelled', name='servicestatus'), nullable=True),
    sa.Column('to_status', sa.Enum('received', 'scheduled', 'in_progress', 'on_hold_parts', 'rescheduled', 'on_hold_client', 'external_work', 'completed', 'delivered', 'cancelled', name='servicestatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parts_order_id', sa.UUID(), nullable=False),
    sa.Column('part_code', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['part_code'], ['part_catalog.part_code'], ),
    sa.ForeignKeyConstraint(['parts_order_id'], ['parts_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_order_receptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('mileage_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gas_level', sa.String(length=50), nullable=True),
    sa.Column('customer_notes', sa.String(length=1000), nullable=True),
    sa.Column('warranty_warnings', sa.String(length=2000), nullable=True),
    sa.Column('damage_photos_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reception_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('vehicle_lifecycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('RECEPCION', 'ENTREGA', 'CAMBIO_PROPIETARIO', 'MANTENIMIENTO', 'GARANTIA', 'ACCIDENTE', 'ROBO_RECUPERADO', 'RESETEO_ODOMETRO', 'INSPECCION_TECNICA', 'NOTA_TECNICA', name='lifecycleeventtype'), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('km_at_event', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('linked_order_id', sa.UUID(), nullable=True),
    sa.Column('created_by_telegram_id', sa.String(length=50), nullable=True),
    sa.Column('is_automatic', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['linked_order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_lifecycle_vehicle_id'), 'vehicle_lifecycle', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_lifecycle_vehicle_id'), table_name='vehicle_lifecycle')
    op.drop_table('vehicle_lifecycle')
    op.drop_table('service_order_receptions')
    op.drop_table('parts_order_items')
    op.drop_table('order_history')
    op.drop_table('service_orders')
    op.drop_table('parts_orders')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('purchase_order_items')
    op.drop_table('vin_master')
    op.drop_table('vehicle_limited_warranties')
    op.drop_table('tenants')
    op.drop_table('purchase_orders')
    op.drop_table('part_catalog')
    op.drop_table('mandatory_maintenance_schedules')
    # ### end Alembic commands ###
