"""fase2 staging

Revision ID: 890fe5b18174
Revises: f7f1699c102d
Create Date: 2026-09-21 20:53:22.659095

Phase 1 "Staging Schema" (sdd/motored-pedidos-ingesta, Fase 2 "Ingesta").
Creates the 4 new staging tables from design §Schema: `carga_archivo`
(with `latido_en`/ADR-1b, `periodo_desde`/`periodo_hasta`/ADR-9, no
`job_id`), `carga_error`, `carga_fila_staging` (ADR-2), and
`retencion_ejecucion` (ADR-3). Autogenerated then reviewed against the
design's exact column/index list -- no manual edits were needed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '890fe5b18174'
down_revision: Union[str, None] = 'f7f1699c102d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_retencion_ejecucion() -> None:
    op.create_table(
        'retencion_ejecucion',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tabla', sa.String(length=64), nullable=False),
        sa.Column('ejecutado_en', sa.DateTime(), nullable=False),
        sa.Column('fecha_limite', sa.Date(), nullable=False),
        sa.Column('filas_eliminadas', sa.Integer(), nullable=False),
        sa.Column('duracion_ms', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_retencion_ejecucion_tabla_ejecutado_en',
        'retencion_ejecucion', ['tabla', 'ejecutado_en'], unique=False,
    )


def _create_carga_archivo() -> None:
    op.create_table(
        'carga_archivo',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tipo', sa.String(length=32), nullable=True),
        sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
        sa.Column('hash_sha256', sa.String(length=64), nullable=False),
        sa.Column('ruta_objeto', sa.String(length=500), nullable=False),
        sa.Column('bytes', sa.Integer(), nullable=False),
        sa.Column('estado', sa.String(length=16), nullable=False),
        sa.Column('filas_leidas', sa.Integer(), nullable=False),
        sa.Column('filas_validas', sa.Integer(), nullable=False),
        sa.Column('filas_rechazadas', sa.Integer(), nullable=False),
        sa.Column('periodo_desde', sa.Date(), nullable=True),
        sa.Column('periodo_hasta', sa.Date(), nullable=True),
        sa.Column('lotes_staged', sa.Integer(), nullable=False),
        sa.Column('ultimo_lote_aplicado', sa.Integer(), nullable=False),
        sa.Column('latido_en', sa.DateTime(timezone=True), nullable=True),
        sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('subido_por', sa.UUID(), nullable=True),
        sa.Column('aplicado_en', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subido_por'], ['usuario.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_carga_archivo_estado_latido_en', 'carga_archivo', ['estado', 'latido_en'],
        unique=False, postgresql_where=sa.text('latido_en IS NOT NULL'),
    )
    op.create_index('ix_carga_archivo_hash_sha256', 'carga_archivo', ['hash_sha256'], unique=False)
    op.create_index(
        'ix_carga_archivo_tipo_estado_created_at',
        'carga_archivo', ['tipo', 'estado', 'created_at'], unique=False,
    )


def _create_carga_error() -> None:
    op.create_table(
        'carga_error',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('carga_id', sa.UUID(), nullable=False),
        sa.Column('fila', sa.Integer(), nullable=False),
        sa.Column('columna', sa.String(length=100), nullable=True),
        sa.Column('valor', sa.String(length=500), nullable=True),
        sa.Column('codigo_error', sa.String(length=32), nullable=False),
        sa.Column('mensaje', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['carga_id'], ['carga_archivo.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_carga_error_carga_id_codigo_error', 'carga_error', ['carga_id', 'codigo_error'], unique=False,
    )


def _create_carga_fila_staging() -> None:
    op.create_table(
        'carga_fila_staging',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('carga_id', sa.UUID(), nullable=False),
        sa.Column('fila', sa.Integer(), nullable=False),
        sa.Column('lote', sa.Integer(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('sucursal_id', sa.UUID(), nullable=True),
        sa.Column('referencia_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['carga_id'], ['carga_archivo.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['referencia_id'], ['referencia.id']),
        sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('carga_id', 'fila', name='uq_carga_fila_staging_carga_id_fila'),
    )
    op.create_index(
        'ix_carga_fila_staging_carga_id_lote', 'carga_fila_staging', ['carga_id', 'lote'], unique=False,
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Split into one helper per table (gga flagged the original single
    # 67-line upgrade()) -- same DDL, same order, no behavior change.
    _create_retencion_ejecucion()
    _create_carga_archivo()
    _create_carga_error()
    _create_carga_fila_staging()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carga_fila_staging_carga_id_lote', table_name='carga_fila_staging')
    op.drop_table('carga_fila_staging')
    op.drop_index('ix_carga_error_carga_id_codigo_error', table_name='carga_error')
    op.drop_table('carga_error')
    op.drop_index('ix_carga_archivo_tipo_estado_created_at', table_name='carga_archivo')
    op.drop_index('ix_carga_archivo_hash_sha256', table_name='carga_archivo')
    op.drop_index('ix_carga_archivo_estado_latido_en', table_name='carga_archivo', postgresql_where=sa.text('latido_en IS NOT NULL'))
    op.drop_table('carga_archivo')
    op.drop_index('ix_retencion_ejecucion_tabla_ejecutado_en', table_name='retencion_ejecucion')
    op.drop_table('retencion_ejecucion')
    # ### end Alembic commands ###
