"""add missing masters fields per spec audit

Revision ID: f7f1699c102d
Revises: 3b4d0ddec0a9
Create Date: 2026-09-16 10:46:15.578911

Post-archive correction (sdd/motored-pedidos-cimientos): closes 16 gaps
found by a full audit against the source spec
(ESPECIFICACION_MOTORED_PEDIDOS.md §4.1) -- 6 new `sucursal` columns, 1 new
`proveedor` column, 1 new `bodega` column, and a genuine RENAME of
`referencia.descripcion` -> `referencia.nombre` (the spec's actual field
name) plus a new `referencia.linea_comercial` column.

`referencia.descripcion`/`nombre` is a RENAME, not a drop+add, even though
autogenerate detects it as two separate operations (it cannot infer
renames) -- manually rewritten here to `op.alter_column(...,
new_column_name=...)` in both directions so no data would be lost if this
ran against a table that already had rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f1699c102d'
down_revision: Union[str, None] = '3b4d0ddec0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodega', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.add_column('proveedor', sa.Column('dias_seguridad_default', sa.Numeric(precision=5, scale=2), nullable=True))
    # Genuine rename (manually fixed -- autogenerate emitted a drop+add pair
    # here, replaced with alter_column so no data is lost).
    op.alter_column('referencia', 'descripcion', new_column_name='nombre')
    op.add_column('referencia', sa.Column('linea_comercial', sa.String(length=60), nullable=True))
    op.add_column('sucursal', sa.Column('dias_empaque', sa.Integer(), nullable=True))
    op.add_column('sucursal', sa.Column('dias_transito', sa.Integer(), nullable=True))
    op.add_column('sucursal', sa.Column('bodega_principal', sa.String(length=50), nullable=True))
    op.add_column('sucursal', sa.Column('departamento', sa.String(length=120), nullable=True))
    op.add_column('sucursal', sa.Column('ciudad', sa.String(length=120), nullable=True))
    op.add_column('sucursal', sa.Column('fecha_apertura', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sucursal', 'fecha_apertura')
    op.drop_column('sucursal', 'ciudad')
    op.drop_column('sucursal', 'departamento')
    op.drop_column('sucursal', 'bodega_principal')
    op.drop_column('sucursal', 'dias_transito')
    op.drop_column('sucursal', 'dias_empaque')
    op.drop_column('referencia', 'linea_comercial')
    # Mirrors the upgrade()'s rename -- reverses nombre -> descripcion in
    # place, not a drop+add.
    op.alter_column('referencia', 'nombre', new_column_name='descripcion')
    op.drop_column('proveedor', 'dias_seguridad_default')
    op.drop_column('bodega', 'descripcion')
    # ### end Alembic commands ###
