"""
Motored inventory counts -- one scan or manual entry
(odd/motored-conteos-inventario, WU3; design §4.5, ADR-5, §7).

`id` is generated by the DEVICE (ADR-5): retries insert with
`ON CONFLICT (id) DO NOTHING`, so a reading is never lost or doubled.
`seq` is a server identity used as the live panel's version (ADR-8).

The log is append-only: a correction is a void (`anulada_en`) plus a new
reading. Round 1 readings never carry a reconteo; round 2 readings always
do (`ck_conteo_lectura_ronda_reconteo`). Readings carry a location but no
bodega (owner override: the count is per store).
"""
from sqlalchemy import (
    BigInteger, CheckConstraint, Column, DateTime, ForeignKey, Identity,
    Index, Numeric, SmallInteger, String, UniqueConstraint, func, text,
)
from sqlalchemy.dialects.postgresql import UUID

from app.motored.database import MotoredBase
from app.motored.models.conteo import lista_sql

METODOS = ("ESCANER", "CAMARA", "MANUAL")
CANTIDAD_MAXIMA = 99999


class ConteoLectura(MotoredBase):
    __tablename__ = "conteo_lectura"
    __table_args__ = (
        UniqueConstraint("seq", name="uq_conteo_lectura_seq"),
        CheckConstraint(
            f"cantidad > 0 AND cantidad <= {CANTIDAD_MAXIMA}",
            name="ck_conteo_lectura_cantidad"),
        CheckConstraint(
            "(ronda = 1 AND reconteo_id IS NULL) "
            "OR (ronda = 2 AND reconteo_id IS NOT NULL)",
            name="ck_conteo_lectura_ronda_reconteo"),
        CheckConstraint(
            f"metodo IN {lista_sql(METODOS)}",
            name="ck_conteo_lectura_metodo"),
        Index(
            "ix_conteo_lectura_agregado",
            "conteo_id", "ronda", "referencia_id",
            postgresql_include=["cantidad"],
            postgresql_where=text("anulada_en IS NULL"),
        ),
        Index(
            "ix_conteo_lectura_conteo_seq", "conteo_id", text("seq DESC")),
        Index(
            "ix_conteo_lectura_sesion_seq", "sesion_id", text("seq DESC")),
        Index(
            "ix_conteo_lectura_conteo_ubicacion",
            "conteo_id", "ubicacion_id",
            postgresql_where=text("anulada_en IS NULL"),
        ),
    )

    id = Column(UUID(as_uuid=True), primary_key=True)
    seq = Column(BigInteger, Identity(always=True), nullable=False)
    conteo_id = Column(
        UUID(as_uuid=True),
        ForeignKey("conteo.id", ondelete="CASCADE"),
        nullable=False,
    )
    sesion_id = Column(
        UUID(as_uuid=True),
        ForeignKey("conteo_sesion.id", ondelete="CASCADE"),
        nullable=False,
    )
    ubicacion_id = Column(
        UUID(as_uuid=True),
        ForeignKey("ubicacion_inventario.id", ondelete="RESTRICT"),
        nullable=False,
    )
    referencia_id = Column(
        UUID(as_uuid=True),
        ForeignKey("referencia.id", ondelete="RESTRICT"),
        nullable=True,
    )
    codigo_leido = Column(String(100), nullable=False)
    cantidad = Column(Numeric(12, 2), nullable=False)
    ronda = Column(SmallInteger, nullable=False, default=1)
    reconteo_id = Column(
        UUID(as_uuid=True),
        ForeignKey("conteo_reconteo.id", ondelete="CASCADE"),
        nullable=True,
    )
    metodo = Column(String(8), nullable=False)
    leida_en = Column(DateTime(timezone=True), nullable=False)
    recibida_en = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now())
    anulada_en = Column(DateTime(timezone=True), nullable=True)
